version: '3.5'
services:
  sboard.postgres:
    image: postgres:14-alpine
    container_name: sboard.postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test
      POSTGRES_DB: sboard
    ports:
      - 5432:5432
    volumes:
      - sboard.postgres:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d sboard" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - sboard

  sboard.pgadmin:
    image: dpage/pgadmin4
    container_name: sboard.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@mail.com"
      PGADMIN_DEFAULT_PASSWORD: "test"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - 8082:80
    networks:
      - sboard

volumes:
  sboard.postgres:

networks:
  sboard:
    driver: bridge
